www:
  #build: www
  image: alexk7898/velotur:www-master
  ports:
    - "80:80"
  volumes:
    - ./www/app:/app
  external_links:
    - dev_mysql:mysql
  links:
    - smtp:smtp
  environment:
      PHPBEE_DEBUG: 1
smtp:
  build: mailtrap
