www:
  build: www
  #image: alexk7898/velotur:www-master
  ports:
    - "80:80"
  volumes:
    - ./www/app:/app
    - ./www/api:/api
  links:
    - smtp:smtp
    - "mysql:mysql"
  environment:
      PHPBEE_DEBUG: 1
smtp:
  build: mailtrap
mysql:
  image: mysql:5.6
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  volumes:
    - ./mysql:/mysql
  ports:
    - "3306:3306"
  command: mysqld --explicit_defaults_for_timestamp=On
