www:
  #build: www
  image: alexk7898/velotur:www-master
  ports:
    - "80:80"
  volumes:
    - ./www/app:/app
  links:
    - smtp:smtp
  extra_hosts:
    - "mysql:127.0.0.1"
  environment:
      PHPBEE_DEBUG: 1
smtp:
  build: mailtrap
