www:
  build: www
  ports:
    - "80:80"
  volumes:
    - ./www/app:/app
  links:
    - mysql:mysql
    - smtp:smtp
  environment:
      PHPBEE_DEBUG: 1
mysql:
  image: tutum/mysql:latest
  #ports:
  #  - "3306:3306"
  volumes:
    #- /var/lib/mysql
    - ./mysqltest:/mysql
smtp:
  build: mailtrap
