www:
  build: www
  ports:
    - "8084:80"
  volumes:
    - ./www/app:/app
  external_links:
    - mysql_dev:mysql
  links:
    - smtp:smtp
  environment:
      PHPBEE_DEBUG: 1
smtp:
  build: mailtrap
