www:
  build: www
  ports:
    - "80:80"
  volumes:
    - ./www/app:/app
  links:
    - mysql:mysql
    - smtp:smtp
mysql:
  image: tutum/mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
    - ./mysql:/mysql
smtp:
  build: exim4
