www:
  build: www
  ports:
    - "8088:80"
  volumes:
    - /home/activeinfo/velotur.ru/public_html/files:/app/public/files
#    - /home/activeinfo/velotur.ru/public_html/content:/app/public/content
    - /home/activeinfo/velotur.ru/FUDforum:/app/FUDforum
    - /home/activeinfo/velotur.ru/public_html/forum:/app/public/forum
  extra_hosts:
    - "mysql:172.17.0.1"
  links:
    - smtp:smtp
smtp:
  build: exim4
