www:
  build: www
  ports:
    - "80:80"
  volumes:
    - /data/public/files:/app/public/files
  links:
    - smtp:smtp
    - mysql:mysql
smtp:
  build: mailtrap
mysql:
  image: tutum/mysql:latest
  volumes:
    - /root/mysqltest:/mysql
